source "%val{config}/plugins/plug.kak/rc/plug.kak"


# Plugins ----------------------------------------------------

plug "andreyorst/plug.kak" noload
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    lsp-enable
}
plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
}
plug "andreyorst/fzf.kak" defer fzf-file %{
    set-option global fzf_file_command 'fd'
}
plug "postsolar/jump.kak"
plug "gustavo-hms/luar" config %{
    require-module luar
}
plug "anhsirk0/kakoune-themes" theme config %{
    colorscheme ayu-dark
}

# Load local plugins
evaluate-commands %sh{
    for f in "$kak_config"/scripts/*.kak; do
        echo "source ${f}"
    done
}


# Visuals --------------------------------------------------------------

set-option global ui_options terminal_assistant=off

map global normal <c-/> ':comment-line<ret>'

add-highlighter global/ show-matching

# Always leave 5 lines visible above and below the cursor
set-option global scrolloff 5,5


# Custom commands -----------------------------------------------------

define-command dba -docstring "delete all buffers" %{
  evaluate-commands %sh{
    for b in $kak_buflist; do
      printf 'delete-buffer %s\n' "$b"
    done
  }
}

def pipe-to-wlclipboard %{
    exec %sh{
        printf %s "$kak_selection" | wl-copy > /dev/null 2>&1 &
    }
}


# Keybinds ------------------------------------------------------------

map global normal <c-/> ':comment-line<ret>'

map global user h ':lsp-hover<ret>'           -docstring 'show hover information'

# custom function above
map global user y ':pipe-to-wlclipboard<ret>' -docstring 'copy selection to wl-clipboard'
map global user p '|wl-paste<ret>'            -docstring 'paste selection from wl-clipboard'

# kaklsp
map global user s ':enter-user-mode lsp<ret>'
map global user r ':lsp-rename-prompt<ret>'   -docstring 'rename hovered symbol'

map global user e ':fzf-mode<ret>f'
map global user b ':fzf-mode<ret>b'

map global user d ':git show-diff<ret>'       -docstring 'show/update git diff'
map global user l ':niri-new-window<ret>'     -docstring 'open new window to the right'
map global user j ':niri-new-consume<ret>'    -docstring 'split window vertically'

map global goto p '<esc>:buffer-previous<ret>' -docstring 'previous buffer'
map global goto n '<esc>:buffer-next<ret>'     -docstring 'next buffer'

# Deletes/replaces without yanking
map global normal d <a-d>
map global normal c <a-c>

map global user p '|wl-paste<ret>'             -docstring 'paste selection from wl-clipboard'

# Extend selection up (inverse of shift+c)
# Default is alt+c, but I can't use that
map global normal D '<a-C>'

map global normal <esc> '<esc>:jumpJump<ret>'

map global normal N '<a-n>'

# Makes search case insensitive by default (with caveats: see https://github.com/mawww/kakoune/issues/1272)
map global normal '/' '/(?i)'


# Other ----------------------------------------------------------------

set-option global tabstop 4            # Tab character will be displayed as 4 spaces
set-option global indentwidth 4        # < and > will indent the code by 4 spaces
hook global BufOpenFile .* expandtab   # Use spaces instead of tabs in all buffers
hook global BufNewFile  .* expandtab


# Lean -----------------------------------------------------------------

hook global BufCreate .*\.(lean) %{
  set-option buffer filetype lean
}

hook -group lsp-filetype-lean global BufSetOption filetype=lean %{
    lsp-inlay-diagnostics-enable buffer

    set-face global InlayDiagnosticWarning yellow+di
    set-face global InlayDiagnosticError red+di
    set-face global InlayDiagnosticHint di
    set-face global InlayDiagnosticInfo di

    set-option global tabstop 2
    set-option global indentwidth 2
    set-option global softtabstop 2

    hook -group lsp-filetype-lean buffer NormalIdle .* %{
        lean-get-goal *goal*
        lean-get-term-goal *term-goal*
    }
    hook -group lsp-filetype-lean buffer InsertIdle .* %{
        lean-get-goal *goal*
        lean-get-term-goal *term-goal*
    }
}
