theme = "ayu_evolve"

[editor]
rulers = [80]
mouse = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-ignore = true

# A-...    alt
# C-...    ctrl
# <space>? for help

[keys.normal]
# Disables common navigation buttons to get me used to vim mode
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"
"home" = "no_op"
"end" = "no_op"
"pageup" = "no_op"
"pagedown" = "no_op"
# "d" copies the deleted content by default; I disabled this behaviour
"d" = "delete_selection_noyank"
"c" = "change_selection_noyank"
# Avoid keybind conflict with sway
"A-;" = "no_op"
"C-;" = "flip_selections"

"esc" = "goto_word"
"D" = "copy_selection_on_prev_line"

# See https://github.com/helix-editor/helix/pull/8147
w = "move_next_long_word_start"
b = "move_prev_long_word_start"
e = "move_next_long_word_end"
W = "move_next_sub_word_start"
B = "move_prev_sub_word_start"
E = "move_next_sub_word_end"

[keys.select]
w = "extend_next_long_word_start"
b = "extend_prev_long_word_start"
e = "extend_next_long_word_end"
W = "extend_next_sub_word_start"
B = "extend_prev_sub_word_start"
E = "extend_next_sub_word_end"

# More navigation buttons disabled
[keys.insert]
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"
"home" = "no_op"
"end" = "no_op"
"pageup" = "no_op"
"pagedown" = "no_op"
"del" = "no_op"

[keys.normal."g"]
"w" = "no_op" # Default for goto_word
"k" = "goto_window_top"
"j" = "goto_window_bottom"
"b" = "no_op" # Defaults for goto_window_top/bottom
"t" = "no_op"
