[[language]]
name = "html"
file-types = ["html", "hbs"]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = [ "scls" ]

[[language]]
name = "zig"
auto-format = false

# Snippet system using https://github.com/estin/simple-completion-language-server
[language-server.scls]
command = "$HOME/.cargo/bin/simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20
snippets_first = true
feature_words = true
feature_unicode_input = true
feature_snippets = true
feature_paths = true

[[language]]
name = "lean"
language-servers = [ "scls", "lean" ]

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.pylsp]
command = "pylsp"

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = false
